In [1]:
# Import Dependencies
import pandas as pd
import numpy as np

# for geo charting
import folium

In [2]:
# indexfreedom file
freedom_csv_path = "data/indexfreedom.csv"

In [3]:
# READ freedom.csv
freedom_df = pd.read_csv(freedom_csv_path, encoding="utf-8")
freedom_df.head()

,year,ISO_code,countries,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,...,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank,hf_score,hf_rank,hf_quartile
0,2016,ALB,Albania,Eastern Europe,6.661503,4.547244,4.666508,5.291752,8.920429,10.0,...,4.050196,7.324582,7.074366,6.705863,6.906901,7.54,34.0,7.568140,48.0,2.0
1,2016,DZA,Algeria,Middle East & North Africa,NaN,NaN,NaN,3.819566,9.456254,10.0,...,3.765515,8.523503,7.029528,5.676956,5.268992,4.99,159.0,5.135886,155.0,4.0
2,2016,AGO,Angola,Sub-Saharan Africa,NaN,NaN,NaN,3.451814,8.060260,5.0,...,1.945540,8.096776,6.782923,4.930271,5.518500,5.17,155.0,5.640662,142.0,4.0
3,2016,ARG,Argentina,Latin America & the Caribbean,7.098483,5.791960,4.343930,5.744791,7.622974,10.0,...,3.260044,5.253411,6.508295,5.535831,5.369019,4.84,160.0,6.469848,107.0,3.0
4,2016,ARM,Armenia,Caucasus & Central Asia,NaN,NaN,NaN,5.003205,8.808750,10.0,...,4.575152,9.319612,6.491481,6.797530,7.378069,7.57,29.0,7.241402,57.0,2.0

In [4]:
''# copy the freedom_df and make 'coutnries the index
freedom_country_df = freedom_df.copy()
freedom_country_df.set_index(['countries'], inplace=True)
freedom_country_df.head()

,year,ISO_code,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,pf_ss_disappearances_violent,...,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank,hf_score,hf_rank,hf_quartile
countries,,,,,,,,,,,,,,,,,,,,,
Albania,2016,ALB,Eastern Europe,6.661503,4.547244,4.666508,5.291752,8.920429,10.0,10.00000,...,4.050196,7.324582,7.074366,6.705863,6.906901,7.54,34.0,7.568140,48.0,2.0
Algeria,2016,DZA,Middle East & North Africa,NaN,NaN,NaN,3.819566,9.456254,10.0,9.29403,...,3.765515,8.523503,7.029528,5.676956,5.268992,4.99,159.0,5.135886,155.0,4.0
Angola,2016,AGO,Sub-Saharan Africa,NaN,NaN,NaN,3.451814,8.060260,5.0,10.00000,...,1.945540,8.096776,6.782923,4.930271,5.518500,5.17,155.0,5.640662,142.0,4.0
Argentina,2016,ARG,Latin America & the Caribbean,7.098483,5.791960,4.343930,5.744791,7.622974,10.0,10.00000,...,3.260044,5.253411,6.508295,5.535831,5.369019,4.84,160.0,6.469848,107.0,3.0
Armenia,2016,ARM,Caucasus & Central Asia,NaN,NaN,NaN,5.003205,8.808750,10.0,10.00000,...,4.575152,9.319612,6.491481,6.797530,7.378069,7.57,29.0,7.241402,57.0,2.0

In [5]:
freedom_country_df['year'].value_counts()

2016    162
2015    162
2014    162
2013    162
2012    162
2011    162
2010    162
2009    162
2008    162
Name: year, dtype: int64

# Visualising Geospatial data withÂ Python
Using Folium to visualize geospation data with Python is taken from this source: 
* https://medium.com/datadriveninvestor/visualising-geospatial-data-with-python-d3b1c519f31
* http://localhost:8888/tree/Visualising-Geospatial-data-with-Python-master 

The above interface is deprecated but still works
upgrade to use class 
* https://github.com/python-visualization/folium/blob/master/examples/GeoJSON_and_choropleth.ipynb
* https://en.wikipedia.org/wiki/GeoJSON

## Setting data for plotting.
Create a data frame with just the country codes and the values we want plotted.

In [6]:
#hist_indicator =  'Life expectancy at birth'
hist_year = 2016
#mask1 = data['IndicatorName'].str.contains(hist_indicator) 
mask2 = freedom_country_df['year'].isin([hist_year])

# apply our mask
#stage = freeRegionYear_mean_df[mask1 & mask2]
stage = freedom_country_df[mask2]
stage.head()

,year,ISO_code,region,pf_rol_procedural,pf_rol_civil,pf_rol_criminal,pf_rol,pf_ss_homicide,pf_ss_disappearances_disap,pf_ss_disappearances_violent,...,ef_regulation_business_bribes,ef_regulation_business_licensing,ef_regulation_business_compliance,ef_regulation_business,ef_regulation,ef_score,ef_rank,hf_score,hf_rank,hf_quartile
countries,,,,,,,,,,,,,,,,,,,,,
Albania,2016,ALB,Eastern Europe,6.661503,4.547244,4.666508,5.291752,8.920429,10.0,10.00000,...,4.050196,7.324582,7.074366,6.705863,6.906901,7.54,34.0,7.568140,48.0,2.0
Algeria,2016,DZA,Middle East & North Africa,NaN,NaN,NaN,3.819566,9.456254,10.0,9.29403,...,3.765515,8.523503,7.029528,5.676956,5.268992,4.99,159.0,5.135886,155.0,4.0
Angola,2016,AGO,Sub-Saharan Africa,NaN,NaN,NaN,3.451814,8.060260,5.0,10.00000,...,1.945540,8.096776,6.782923,4.930271,5.518500,5.17,155.0,5.640662,142.0,4.0
Argentina,2016,ARG,Latin America & the Caribbean,7.098483,5.791960,4.343930,5.744791,7.622974,10.0,10.00000,...,3.260044,5.253411,6.508295,5.535831,5.369019,4.84,160.0,6.469848,107.0,3.0
Armenia,2016,ARM,Caucasus & Central Asia,NaN,NaN,NaN,5.003205,8.808750,10.0,10.00000,...,4.575152,9.319612,6.491481,6.797530,7.378069,7.57,29.0,7.241402,57.0,2.0

In [7]:
data_to_plot = stage[['ISO_code','hf_score']]
data_to_plot.head()

          ISO_code  hf_score
countries
Albania        ALB  7.568140
Algeria        DZA  5.135886
Angola         AGO  5.640662
Argentina      ARG  6.469848
Armenia        ARM  7.241402

## Label for the map

In [8]:
legendTitle = "HF Score by Country"

# Visualising the Map

In [9]:
## Country coordinates for plotting
country_geo = 'data/world-countries.json'

In [10]:
map = folium.Map(location=[100, 0], zoom_start=1.5)

In [11]:
# choropleth maps bind Pandas Data Frames and json geometries.
map.choropleth(geo_data=country_geo, data=data_to_plot,
             columns=['ISO_code','hf_score'],
             key_on='feature.id',
             fill_color='RdYlBu', fill_opacity=0.7, line_opacity=0.2,
             legend_name=legendTitle)

C:\Users\jimco\Anaconda3\envs\PythonData\lib\site-packages\folium\folium.py:415: FutureWarning: The choropleth  method has been deprecated. Instead use the new Choropleth class, which has the same arguments. See the example notebook 'GeoJSON_and_choropleth' for how to do this.
  FutureWarning

In [12]:
#html_file = 'freedomplot_hfscore.html'
map.save('plots/freedomplot_hfscore.html')

In [13]:
# Import the Folium interactive html file
from IPython.display import HTML
HTML('<iframe src=freedomplot_hfscore.html width=700 height=450></iframe>')

C:\Users\jimco\Anaconda3\envs\PythonData\lib\site-packages\IPython\core\display.py:694: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")