In [34]:
import pandas as pd
import numpy as np

In [35]:
#read in the csv
happy_csv = "data/world-happiness-report-2019.csv"

In [36]:
#create dataframe
happy_df = pd.read_csv(happy_csv)
happy_df

,Country (region),Ladder,SD of Ladder,Positive affect,Negative affect,Social support,Freedom,Corruption,Generosity,Log of GDP\nper capita,Healthy life\nexpectancy
0,Finland,1,4,41.0,10.0,2.0,5.0,4.0,47.0,22.0,27.0
1,Denmark,2,13,24.0,26.0,4.0,6.0,3.0,22.0,14.0,23.0
2,Norway,3,8,16.0,29.0,3.0,3.0,8.0,11.0,7.0,12.0
3,Iceland,4,9,3.0,3.0,1.0,7.0,45.0,3.0,15.0,13.0
4,Netherlands,5,1,12.0,25.0,15.0,19.0,12.0,7.0,12.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,152,63,54.0,102.0,144.0,21.0,2.0,90.0,132.0,103.0
152,Tanzania,153,122,78.0,50.0,131.0,78.0,34.0,49.0,125.0,118.0
153,Afghanistan,154,25,152.0,133.0,151.0,155.0,136.0,137.0,134.0,139.0
154,Central African Republic,155,117,132.0,153.0,155.0,133.0,122.0,113.0,152.0,150.0
155,South Sudan,156,140,127.0,152.0,148.0,154.0,61.0,85.0,140.0,143.0

In [37]:
#rename last two columns for clarity 
happy_df.rename(columns={'Log of GDP\nper capita': 'Log of GDP per capita', 'Healthy life\nexpectancy': 'Healthy life expectancy'}, inplace=True)
happy_df

,Country (region),Ladder,SD of Ladder,Positive affect,Negative affect,Social support,Freedom,Corruption,Generosity,Log of GDP per capita,Healthy life expectancy
0,Finland,1,4,41.0,10.0,2.0,5.0,4.0,47.0,22.0,27.0
1,Denmark,2,13,24.0,26.0,4.0,6.0,3.0,22.0,14.0,23.0
2,Norway,3,8,16.0,29.0,3.0,3.0,8.0,11.0,7.0,12.0
3,Iceland,4,9,3.0,3.0,1.0,7.0,45.0,3.0,15.0,13.0
4,Netherlands,5,1,12.0,25.0,15.0,19.0,12.0,7.0,12.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,152,63,54.0,102.0,144.0,21.0,2.0,90.0,132.0,103.0
152,Tanzania,153,122,78.0,50.0,131.0,78.0,34.0,49.0,125.0,118.0
153,Afghanistan,154,25,152.0,133.0,151.0,155.0,136.0,137.0,134.0,139.0
154,Central African Republic,155,117,132.0,153.0,155.0,133.0,122.0,113.0,152.0,150.0
155,South Sudan,156,140,127.0,152.0,148.0,154.0,61.0,85.0,140.0,143.0

In [38]:
#set country as the new index 
happy_df = happy_df.set_index(['Country (region)'])
happy_df

,Ladder,SD of Ladder,Positive affect,Negative affect,Social support,Freedom,Corruption,Generosity,Log of GDP per capita,Healthy life expectancy
Country (region),,,,,,,,,,
Finland,1,4,41.0,10.0,2.0,5.0,4.0,47.0,22.0,27.0
Denmark,2,13,24.0,26.0,4.0,6.0,3.0,22.0,14.0,23.0
Norway,3,8,16.0,29.0,3.0,3.0,8.0,11.0,7.0,12.0
Iceland,4,9,3.0,3.0,1.0,7.0,45.0,3.0,15.0,13.0
Netherlands,5,1,12.0,25.0,15.0,19.0,12.0,7.0,12.0,18.0
...,...,...,...,...,...,...,...,...,...,...
Rwanda,152,63,54.0,102.0,144.0,21.0,2.0,90.0,132.0,103.0
Tanzania,153,122,78.0,50.0,131.0,78.0,34.0,49.0,125.0,118.0
Afghanistan,154,25,152.0,133.0,151.0,155.0,136.0,137.0,134.0,139.0
Central African Republic,155,117,132.0,153.0,155.0,133.0,122.0,113.0,152.0,150.0
South Sudan,156,140,127.0,152.0,148.0,154.0,61.0,85.0,140.0,143.0

In [39]:
#dropping NaN values still leaves us with 140 values
print(f"Original data shape: {happy_df.shape}")
print(f"No NaN shape: {happy_df.dropna().shape}")

Original data shape: (156, 10)
No NaN shape: (140, 10)